name: Database Migration Tests

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'migrations/**'
      - 'server/db/**'

jobs:
  test-migrations:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: testpass
          MYSQL_DATABASE: heartguard_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run migration tests
      run: npm run test:migrations
      env:
        DATABASE_URL: mysql://root:testpass@localhost:3306/heartguard_test

    - name: Run schema health checks
      run: npm run check:schema
      env:
        DATABASE_URL: mysql://root:testpass@localhost:3306/heartguard_test

    - name: Upload logs
      uses: actions/upload-artifact@v3
      with:
        name: migration-logs
        path: |
          *.log
          test-results.xml